# ============================================================
# GENERAL
# ============================================================

set -g mouse on
set -g status-position bottom
set -g status-interval 5

# ============================================================
# STATUSLINE
# ============================================================

set -g status-style "bg=#131314,fg=#e5e2e2"

# Left: session name
set -g status-left-length 30
set -g status-left "#[bg=#c4c6ce,fg=#131314,bold] #S #[bg=#201f20,fg=#e5e2e2]"

# Windows
setw -g window-status-format " #[fg=#909095]#I:#W "
setw -g window-status-current-format "#[bg=#2a2a2a,fg=#e5e2e2,bold] #I:#W "

# Right: date + time
set -g status-right-length 50
set -g status-right "#[bg=#201f20,fg=#c6c6cb] %Y-%m-%d %H:%M #[default]"
source-file -q "$HOME/.config/tmux/themes/noctalia.conf"
