# ============================================================
# GENERAL
# ============================================================

set -g mouse on
set -g status-position bottom
set -g status-interval 5

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty*:Tc"
set -ag terminal-overrides ",xterm-kitty*:RGB"

set -g allow-passthrough on

# ============================================================
# THEME
# ============================================================

# Optional transparency for our custom statusline
set -g @noctalia_status_transparent 0

# Noctalia-generated palette

# Our custom Tokyo-Night-inspired statusline
source-file -q "$HOME/.config/tmux/themes/noctalia.conf"
run-shell "$HOME/.config/tmux/themes/noctalia-status.tmux"
run-shell -b "$HOME/.config/tmux/scripts/hot-reload.sh"
