set -g mouse on
set -g status-position bottom
set -g status-interval 5
set -sg escape-time 10

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty*:Tc"
set -ag terminal-overrides ",xterm-kitty*:RGB"

set -g allow-passthrough on
