set -g mouse on
set -g status-position bottom
set -g status-interval 5
set -sg escape-time 10

bind-key X confirm-before -p "kill window #W? (y/n)" kill-window
bind-key S confirm-before -p "kill session #S? (y/n)" kill-session
bind-key Q confirm-before -p "kill server? (y/n)" kill-server

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-kitty*:Tc"
set -ag terminal-overrides ",xterm-kitty*:RGB"

set -g allow-passthrough on
