# Optional transparency for our custom statusline
set -g @noctalia_status_transparent 0

# Noctalia-generated palette

# Our custom Tokyo-Night-inspired statusline
source-file -q "$HOME/.config/tmux/themes/noctalia.conf"
run-shell "$HOME/.config/tmux/themes/noctalia-status.tmux"
run-shell -b "$HOME/.config/tmux/scripts/hot-reload.sh"
